/*********************************************************************
HTTP Application callback source file 

Company:
   Microchip Technology Inc. 

File Name:
   http_print.c

Description: 
   Provides callback headers and resolution for user's custom
   HTTP Application.
   
   This file is automatically generated by the MPFS Utility
   ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
   
*********************************************************************/

/*********************************************************************
Copyright (C) 2012-2018 Microchip Technology Inc. and its subsidiaries 
 Microchip Technology Inc. and its subsidiaries.
 Subject to your compliance with these terms, you may use Microchip software
 and any derivatives exclusively with Microchip products. It is your
 responsibility to comply with third party license terms applicable to your
 use of third party software (including open source software) that may
 accompany Microchip software.

 THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
 EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
 WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR
 PURPOSE.
 
 IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
 INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
 WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
 BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
 FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
 ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *********************************************************************/

#include "tcpip/tcpip.h"

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID);
void TCPIP_HTTP_Print_config_devmode(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_saveconfig(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_countrycode(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_stassid(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_stapwd(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_staauth(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_stachannel(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_autoconnect(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_apssid(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_appwd(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_apauth(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_apchannel(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_ssidv(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_config_mac(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_hostname(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_ip(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_gw(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_subnet(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_dns1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_dns2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_version(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_builddate(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_hellomsg(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_pot(HTTP_CONN_HANDLE connHandle);

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID)
{
    TCP_SOCKET sktHTTP; 
    switch(callbackID)
    {
        case 0x00000000:
			TCPIP_HTTP_FileInclude(connHandle,(const uint8_t *)"header.inc");
			break;
        case 0x00000001:
			TCPIP_HTTP_Print_config_devmode(connHandle,0);
			break;
        case 0x00000002:
			TCPIP_HTTP_Print_config_devmode(connHandle,1);
			break;
        case 0x00000003:
			TCPIP_HTTP_Print_config_saveconfig(connHandle,1);
			break;
        case 0x00000004:
			TCPIP_HTTP_Print_config_saveconfig(connHandle,0);
			break;
        case 0x00000005:
			TCPIP_HTTP_Print_config_countrycode(connHandle,0);
			break;
        case 0x00000006:
			TCPIP_HTTP_Print_config_countrycode(connHandle,1);
			break;
        case 0x00000007:
			TCPIP_HTTP_Print_config_countrycode(connHandle,2);
			break;
        case 0x00000008:
			TCPIP_HTTP_Print_config_countrycode(connHandle,3);
			break;
        case 0x00000009:
			TCPIP_HTTP_Print_config_stassid(connHandle);
			break;
        case 0x0000000a:
			TCPIP_HTTP_Print_config_stapwd(connHandle);
			break;
        case 0x0000000b:
			TCPIP_HTTP_Print_config_staauth(connHandle,1);
			break;
        case 0x0000000c:
			TCPIP_HTTP_Print_config_staauth(connHandle,3);
			break;
        case 0x0000000d:
			TCPIP_HTTP_Print_config_staauth(connHandle,5);
			break;
        case 0x0000000e:
			TCPIP_HTTP_Print_config_staauth(connHandle,6);
			break;
        case 0x0000000f:
			TCPIP_HTTP_Print_config_stachannel(connHandle);
			break;
        case 0x00000010:
			TCPIP_HTTP_Print_config_autoconnect(connHandle,1);
			break;
        case 0x00000011:
			TCPIP_HTTP_Print_config_autoconnect(connHandle,0);
			break;
        case 0x00000012:
			TCPIP_HTTP_Print_config_apssid(connHandle);
			break;
        case 0x00000013:
			TCPIP_HTTP_Print_config_appwd(connHandle);
			break;
        case 0x00000014:
			TCPIP_HTTP_Print_config_apauth(connHandle,1);
			break;
        case 0x00000015:
			TCPIP_HTTP_Print_config_apauth(connHandle,3);
			break;
        case 0x00000016:
			TCPIP_HTTP_Print_config_apauth(connHandle,4);
			break;
        case 0x00000017:
			TCPIP_HTTP_Print_config_apauth(connHandle,5);
			break;
        case 0x00000018:
			TCPIP_HTTP_Print_config_apauth(connHandle,6);
			break;
        case 0x00000019:
			TCPIP_HTTP_Print_config_apchannel(connHandle);
			break;
        case 0x0000001a:
			TCPIP_HTTP_Print_config_ssidv(connHandle,1);
			break;
        case 0x0000001b:
			TCPIP_HTTP_Print_config_ssidv(connHandle,0);
			break;
        case 0x0000001c:
			TCPIP_HTTP_Print_config_mac(connHandle);
			break;
        case 0x0000001d:
			TCPIP_HTTP_Print_config_hostname(connHandle);
			break;
        case 0x0000001e:
			TCPIP_HTTP_Print_config_ip(connHandle);
			break;
        case 0x0000001f:
			TCPIP_HTTP_Print_config_gw(connHandle);
			break;
        case 0x00000020:
			TCPIP_HTTP_Print_config_subnet(connHandle);
			break;
        case 0x00000021:
			TCPIP_HTTP_Print_config_dns1(connHandle);
			break;
        case 0x00000022:
			TCPIP_HTTP_Print_config_dns2(connHandle);
			break;
        case 0x00000023:
			TCPIP_HTTP_FileInclude(connHandle,(const uint8_t *)"footer.inc");
			break;
        case 0x00000024:
			TCPIP_HTTP_Print_version(connHandle);
			break;
        case 0x00000025:
			TCPIP_HTTP_Print_builddate(connHandle);
			break;
        case 0x00000026:
			TCPIP_HTTP_Print_hellomsg(connHandle);
			break;
        case 0x00000027:
			TCPIP_HTTP_Print_pot(connHandle);
			break;
        default:
            // Output notification for undefined values
            sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
            TCPIP_TCP_ArrayPut(sktHTTP, (const uint8_t *)"!DEF", 4);
    }
    return;
}

void TCPIP_HTTP_Print_myVariable(HTTP_CONN_HANDLE connHandle)
{
    TCP_SOCKET sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
    TCPIP_TCP_Put(sktHTTP, '~');
    return;
}
